name = "NQCCalculators"
uuid = "ddd1f41d-9621-41e2-91a4-6b87cc8989f3"
authors = ["Ash Baldwin <Ash.Baldwin@warwick.ac.uk> and contributors"]
version = "1.0.0-DEV"

[deps]
NQCModels = "c814dc9f-a51f-4eaf-877f-82eda4edad48"

[compat]
NQCModels = "0.9.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
