name = "NQCCalculators"
uuid = "ddd1f41d-9621-41e2-91a4-6b87cc8989f3"
authors = ["Ash Baldwin <Ash.Baldwin@warwick.ac.uk> and contributors"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NQCBase = "78c76ebc-5665-4934-b512-82d81b5cbfb7"
NQCModels = "c814dc9f-a51f-4eaf-877f-82eda4edad48"
RingPolymerArrays = "81cd853e-d334-476c-b156-f95acc8a32dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.11.0"
NQCBase = "0.5"
NQCModels = "0.10"
RingPolymerArrays = "0.1.3"
StaticArrays = "1.9.13"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
