#Definitions of Abstract Cache structs
"""
    type: Abstract_Cache{M<:Model}

Top-level type for all caches.

Each concrete cache contains the `Model` and the fields to store the quantities
obtained from the model.
"""
abstract type Abstract_Cache{M<:Model} end #type was called AbstractCalculator

"""
    type: Abstract_ClassicalModel_Cache{T, M<:Union{ClassicalModel, CompositeModel}} <: Abstract_Cache{T, M}

Type for storing quantities obtained from models defined by an analytic classical potentials. Examples
using Base: AbstractArrayOrBroadcasted
include the harmonic potential (AdiabticModels.Harmonic), the morse potential (AdiabticModels.Morse) and
the Darling-Holloway elbow model (AdiabticModels.DarlingHollowayElbow)
"""
abstract type Abstract_ClassicalModel_Cache{M<:Union{ClassicalModel, ClassicalFrictionModel, CompositeModel}} <: Abstract_Cache{M} end #type was called AbstractAdiabaticCalculator

"""
    type: Abstract_QuantumModel_Cache{T, M} <: Abstract_Cache{T, M}

Abstract supertype for all quantum models that can be solved with exact diagonalisation.
"""
abstract type Abstract_QuantumModel_Cache{M<:Union{QuantumModel, QuantumFrictionModel}} <: Abstract_Cache{M} end #type was called AbstractDiabaticCalculator

"""
   type: Abstract_CorrelatedQuantumModel_Cache{T, M<:{CorrelatedQuantumModel}} <: Abstract_Cache{T, M}

    Type for storing quantities obtained from models defined in terms of quantum Hamiltonians that parameterise a collection of
    interacting electrons and therefore cannot be solved with exact diagonalisation.
"""
abstract type Abstract_CorrelatedQuantumModel_Cache{M} <: Abstract_QuantumModel_Cache{M} end #type didn't formerly exist

function Base.show(io::Core.IO, cache::Abstract_Cache)
	printstyled(io, string(typeof(cache))*"\n"; bold=true)
	for field in fieldnames(typeof(cache))
		printstyled(io, "$(field):\n"; underline=true)
		Base.show(io, getfield(cache, field))
		print(io, "\n")
	end
end

#Definitions for the concrete Subtypes of the above Cache Types
"""
    struct: ClassicalModel_Cache{T,M} <: Abstract_ClassicalModel_Cache{T,M}
        model::{ClassicalModel, CompositeModel}
        potential::T,Matrix{T}}
        derivative::Matrix{T},Matrix{T}}


Struct of type Abstract_ClassicalModel_Cache, used to store quantities (of data type `T`) generated by its input model `M`.
"""
struct ClassicalModel_Cache{M,Mtx} <: Abstract_ClassicalModel_Cache{M}
    model::M #Model from NQCModels
    potential::Mtx #Matrix
    derivative::Mtx #Matrix
end

Adapt.@adapt_structure ClassicalModel_Cache

"""
    function: ClassicalModel_Cache{T}(model::M, atoms::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice
and the number of atoms in the simulation
"""
function ClassicalModel_Cache(model::M, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {M<:Model, T, N}
    potential = similar_zero(matrix_prototype, 1, 1)
    derivative = similar_zero(matrix_prototype, ndofs(model), atoms)

    return ClassicalModel_Cache(
        model,
        potential,
        derivative
    )
end


"""
    struct: RingPolymer_ClassicalModel_Cache{T,M} <: Abstract_ClassicalModel_Cache{T,M}
        model::M
        potential::Vector{Matrix{T}}
        derivative::Array{T,3}

        centroid::Matrix{T}
        centroid_potential::Hermitian{T,Matrix{T}}
        centroid_derivative::Matrix{Hermitian{T,Matrix{T}}}

Struct of type Abstract_ClassicalModel_Cache, used to store quantities (of data type `T`) generated by its input model `M`.
"""
struct RingPolymer_ClassicalModel_Cache{M, Mtx, VMtx, Arr} <: Abstract_ClassicalModel_Cache{M}
    model::M #Model from NQCModels
    potential::VMtx #Vector of Matricex
    derivative::Arr #3D Array
    centroid::Mtx #Matrix
    centroid_potential::Mtx #Matrix
    centroid_derivative::Mtx #Matrix

end

Adapt.@adapt_structure RingPolymer_ClassicalModel_Cache

"""
    function: RingPolymer_ClassicalModel_Cache{T}(model::M, atoms::Integer, beads::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice,
the number of atoms in the simulation and the number of beads used in the ring polymer simulation.
"""
function RingPolymer_ClassicalModel_Cache(model::M, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {M<:Model, T, N}
    potential = [similar_zero(matrix_prototype, 1, 1) for i in 1:beads]
    derivative = similar_zero(matrix_prototype, ndofs(model), atoms, beads)

    centroid = similar_zero(matrix_prototype, ndofs(model), atoms)
    centroid_potential = similar_zero(matrix_prototype, 1, 1)
    centroid_derivative = similar_zero(matrix_prototype, ndofs(model), atoms)

    return RingPolymer_ClassicalModel_Cache(
        model,
        potential,
        derivative,

        centroid,
        centroid_potential,
        centroid_derivative
    )
end

"""
    struct: ClassicalFrictionModel_Cache{T,M} <: Abstract_ClassicalModel_Cache{T,M}
        model::M
        potential::Matrix{T}
        derivative::Matrix{T},Matrix{T}}
        friction::Matrix{T},Matrix{T}}


Struct of type Abstract_ClassicalModel_Cache, used to store quantities (of data type `T`) generated by its input model `M`.
"""
struct ClassicalFrictionModel_Cache{M, Mtx} <: Abstract_ClassicalModel_Cache{M} #was mutable struct - changed for efficiency, needs testing to determine if this is a code breaking change
    model::M #Model from NQCModels
    potential::Mtx #Matrix
    derivative::Mtx #Matrix
    friction::Mtx #Matrix
end

Adapt.@adapt_structure ClassicalFrictionModel_Cache

"""
    function: ClassicalFrictionModel_Cache{T}(model::M, atoms::Integer) where {T,M<:Model}

Function which constructs and returns the struct of the same name. Takes as input an adiabatic friction model `M` of the users choice and
the number of atoms in the simulation.
"""
function ClassicalFrictionModel_Cache(model::M, atoms::Integer, matrix_prototype::AbstractArray) where {M<:Model}
    potential = similar_zero(matrix_prototype, 1,1)
    derivative = similar_zero(matrix_prototype, ndofs(model), atoms)
    friction = similar_zero(matrix_prototype, ndofs(model)*atoms, ndofs(model)*atoms)

    return ClassicalFrictionModel_Cache(
        model,
        potential,
        derivative,
        friction
    )
end



"""
    struct: RingPolymer_ClassicalFrictionModel_Cache{T,M} <: Abstract_ClassicalModel_Cache{T,M}
        model::M
        potential::Vector{Matrix{T}}
        derivative::Matrix{T}
        friction::Matrix{T}

        centroid::Matrix{T}
        centroid_potential::Hermitian{T,Matrix{T}}
        centroid_derivative::Matrix{Hermitian{T,Matrix{T}}}
        centroid_adiabatic_derivative::Matrix{Matrix{T}}
        centroid_nonadiabatic_coupling::Matrix{Matrix{T}}


Struct of type Abstract_ClassicalModel_Cache, used to store quantities (of data type `T`) generated by its input model `M`.
"""
struct RingPolymer_ClassicalFrictionModel_Cache{M, Arr, Mtx} <: Abstract_ClassicalModel_Cache{M}
    model::M #Model from NQCModels
    potential::Arr #3D Array
    derivative::Arr #3D Array
    friction::Arr #3D Array

    centroid::Mtx #Matrix
    centroid_potential::Mtx #Matrix
    centroid_derivative::Mtx #Matrix
    centroid_friction::Mtx #Matrix
end

Adapt.@adapt_structure RingPolymer_ClassicalFrictionModel_Cache

"""
    function: RingPolymer_ClassicalFrictionModel_Cache{T}(model::M, atoms::Integer, beads::Integer) where {T,M<:Model}

Function which constructs and returns the struct of the same name. Takes as input an adiabatic model `M` of the users choice,
the number of atoms in the simulation and the number of beads used in the ring polymer simulation.
"""
function RingPolymer_ClassicalFrictionModel_Cache(model::M, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray) where {M<:Model}

    potential = similar_zero(matrix_prototype, 1, 1, beads)
    derivative = similar_zero(matrix_prototype, ndofs(model), atoms, beads)
    friction = similar_zero(matrix_prototype, ndofs(model)*atoms, ndofs(model)*atoms, beads)

    centroid = similar_zero(matrix_prototype, ndofs(model), atoms)
    centroid_potential = similar_zero(matrix_prototype, 1,1)
    centroid_derivative = similar_zero(matrix_prototype, ndofs(model), atoms)
    centroid_friction = similar_zero(matrix_prototype, ndofs(model)*atoms, ndofs(model)*atoms)

    return RingPolymer_ClassicalFrictionModel_Cache(
        model,
        potential,
        derivative,
        friction,

        centroid,
        centroid_potential,
        centroid_derivative,
        centroid_friction
    )
end

"""
    struct: QuantumModel_Cache{T,M} <: Abstract_QuantumModel_Cache{T,M}
        model::M
        potential::Hermitian{T,Matrix{T}}
        derivative::Matrix{Hermitian{T,Matrix{T}}}
        eigen::LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}
        adiabatic_derivative::Matrix{Matrix{T}}
        nonadiabatic_coupling::Matrix{Matrix{T}}


Struct of type Abstract_QuantumModel_Cache, used to store quantities (of data types `T`, `S` and `L`) generated by its input model `M`.
"""
struct QuantumModel_Cache{M, HMtx, Mtx, DMtx, Eigs, Vec, } <: Abstract_QuantumModel_Cache{M}
    model::M
    potential::HMtx
    derivative::DMtx
    eigen::Eigs
    phase_ref::Vec
    adiabatic_derivative::DMtx
    nonadiabatic_coupling::DMtx
    tmp_mat::Mtx

end

Adapt.@adapt_structure QuantumModel_Cache

"""
    function: QuantumModel_Cache{T}(model::M, atoms::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice
and the number of atoms in the simulation.
"""
function QuantumModel_Cache(model::M, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {M<:Model, T, N}
    n = nstates(model)
    mat = NQCModels.QuantumModels.matrix_template(model, T)
    vec = NQCModels.QuantumModels.vector_template(model, T)

    potential = similar_zero(matrix_prototype, size(mat))
    derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms]
    eigen = (similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat)))
    phase_ref = similar_but_random(matrix_prototype, n) .+ eps(T)
    adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(derivative)]
    nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(derivative)]
    tmp_mat = similar_zero(matrix_prototype, size(mat))

    return QuantumModel_Cache(
        model,
        potential,
        derivative,
        eigen,
        phase_ref,
        adiabatic_derivative,
        nonadiabatic_coupling,
        tmp_mat
    )
end


"""
    struct: RingPolymer_QuantumModel_Cache{T,M,S,L} <: Abstract_QuantumModel_Cache{T,M}
        model::M
        potential::Hermitian{T,Matrix{T}}
        derivative::Matrix{Hermitian{T,Matrix{T}}}
        eigen::Vector{LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}}
        adiabatic_derivative::Matrix{Matrix{T}}
        nonadiabatic_coupling::Matrix{Matrix{T}}

        traceless_potential::Vector{Hermitian{T,Matrix{T}}}
        V̄::Vector{T}
        traceless_derivative::Array{Hermitian{T,Matrix{T}},3}
        D̄::Array{T,3}
        traceless_adiabatic_derivative::Array{Matrix{T},3}

        centroid::Matrix{T}
        centroid_potential::Hermitian{T,Matrix{T}}
        centroid_derivative::Matrix{Hermitian{T,Matrix{T}}}
        centroid_eigen::LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}
        centroid_adiabatic_derivative::Matrix{Matrix{T}}
        centroid_nonadiabatic_coupling::Matrix{Matrix{T}}



Struct of type Abstract_QuantumModel_Cache, used to store quantities (of data types `T`, `S` and `L`) generated by its input model `M`.
"""
struct RingPolymer_QuantumModel_Cache{M, VHMtx, ArrHMtx, VEig, Vec, ArrMtx, Mtx, Arr, HMtx, MHMtx, Eig, MtxMtx, VecVec} <: Abstract_QuantumModel_Cache{M}
    model::M
    potential::VHMtx #Vector of Hermitian(CPU) Matrices
    derivative::ArrHMtx #3D Array of Hermitian(CPU) Matrices
    eigen::VEig #Vector of eigen structure
    phase_ref::VecVec #Vector
    adiabatic_derivative::ArrMtx #Array of Matrices
    nonadiabatic_coupling::ArrMtx # Array of Matrices
    tmp_mat::Mtx #Matrix

    traceless_potential::VHMtx #Vector of Hermitian(CPU) Matrices
    V̄::Vec #Vector
    traceless_derivative::ArrHMtx #3D Array of Hermitian(CPU) Matrices
    D̄::Arr #Array
    traceless_adiabatic_derivative::ArrMtx #Array of Matrices

    centroid::Mtx #Matrix
    centroid_potential::HMtx #Hermitian(CPU) Matrix
    centroid_derivative::MHMtx #3D Array of Hermitian(CPU) Matrices
    centroid_eigen::Eig #Vector of eigen structure
    centroid_phase_ref::Vec
    centroid_adiabatic_derivative::MtxMtx
    centroid_nonadiabatic_coupling::MtxMtx
end

Adapt.@adapt_structure RingPolymer_QuantumModel_Cache

"""
    function: RingPolymer_QuantumModel_Cache{T}(model::M, atoms::Integer, beads::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice,
the number of atoms in the simulation and the number of beads used in the ring polymer simulation.
"""
function RingPolymer_QuantumModel_Cache(model::M, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {M<:Model, T, N}
    n = nstates(model)
    mat = NQCModels.QuantumModels.matrix_template(model, T)
    vec = NQCModels.QuantumModels.vector_template(model, T)

    potential = [similar_zero(matrix_prototype, size(mat)) for _=1:beads]
    derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    eigen = [(similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat))) for _=1:beads]
    phase_ref = [similar_but_random(matrix_prototype, n) .+ eps(T) for _=1:beads]
    nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    tmp_mat = similar_zero(matrix_prototype, size(mat))

    traceless_potential = [similar_zero(matrix_prototype, size(mat)) for _=1:beads]
    V̄ =similar_zero(vec, beads)
    traceless_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    D̄ = similar_zero(matrix_prototype, ndofs(model), atoms, beads)
    traceless_adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]

    centroid = similar_zero(matrix_prototype, ndofs(model), atoms)
    centroid_potential = similar_zero(matrix_prototype, size(mat))
    centroid_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms]
    centroid_eigen = (similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat)))
    centroid_phase_ref = similar_but_random(matrix_prototype, n) .+ eps(T)
    centroid_adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(centroid_derivative)]
    centroid_nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(centroid_derivative)]

    return RingPolymer_QuantumModel_Cache(
        model,
        potential,
        derivative,
        eigen,
        phase_ref,
        adiabatic_derivative,
        nonadiabatic_coupling,
        tmp_mat,

        traceless_potential,
        V̄,
        traceless_derivative,
        D̄,
        traceless_adiabatic_derivative,

        centroid,
        centroid_potential,
        centroid_derivative,
        centroid_eigen,
        centroid_phase_ref,
        centroid_adiabatic_derivative,
        centroid_nonadiabatic_coupling
    )
end



"""
    struct: QuantumFrictionModel_Cache{T,M} <: Abstract_QuantumModel_Cache{T,M}
        model::M
        potential::Hermitian{T,Matrix{T}}
        derivative::Matrix{Hermitian{T,Matrix{T}}}
        eigen::LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}
        adiabatic_derivative::Matrix{Matrix{T}}
        nonadiabatic_coupling::Matrix{Matrix{T}}


Struct of type Abstract_QuantumModel_Cache, used to store quantities (of data types `T`, `S` and `L`) generated by its input model `M`.
"""
struct QuantumFrictionModel_Cache{M, HMtx, MtxHMtx, Eig, Vec, MtxMtx, Mtx} <: Abstract_QuantumModel_Cache{M}
    model::M
    friction_method::FrictionEvaluationMethod
    potential::HMtx
    derivative::MtxHMtx
    eigen::Eig
    phase_ref::Vec
    adiabatic_derivative::MtxMtx
    nonadiabatic_coupling::MtxMtx
    friction::Mtx
    tmp_mat::Mtx
end

Adapt.@adapt_structure QuantumFrictionModel_Cache

"""
    function: QuantumFrictionModel_Cache{T}(model::M, atoms::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice
and the number of atoms in the simulation.
"""
function QuantumFrictionModel_Cache(model::M, atoms::Integer, matrix_prototype::AbstractArray; friction_method::Union{FrictionEvaluationMethod, Nothing}) where {M<:Model}
    n = nstates(model)
    mat = NQCModels.QuantumModels.matrix_template(model, eltype(matrix_prototype))
    vec = NQCModels.QuantumModels.vector_template(model, eltype(matrix_prototype))

    potential = similar_zero(matrix_prototype, size(mat))
    derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms]
    eigen = (similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat)))
    phase_ref = similar_but_random(matrix_prototype, n) .+ eps(eltype(matrix_prototype))
    adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(derivative)]
    nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(derivative)]
    friction = similar_zero(matrix_prototype, ndofs(model)*atoms, ndofs(model)*atoms)
    tmp_mat = similar_zero(matrix_prototype, size(mat))

    return QuantumFrictionModel_Cache(
        model,
        friction_method,
        potential,
        derivative,
        eigen,
        phase_ref,
        adiabatic_derivative,
        nonadiabatic_coupling,
        friction,
        tmp_mat
    )
end



"""
    struct: RingPolymer_QuantumFrictionModel_Cache{T,M,S,L} <: Abstract_QuantumModel_Cache{T,M}
        model::M
        potential::Hermitian{T,Matrix{T}}
        derivative::Matrix{Hermitian{T,Matrix{T}}}
        eigen::Vector{LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}}
        adiabatic_derivative::Matrix{Matrix{T}}
        nonadiabatic_coupling::Matrix{Matrix{T}}

        traceless_potential::Vector{Hermitian{T,Matrix{T}}}
        V̄::Vector{T}
        traceless_derivative::Array{Hermitian{T,Matrix{T}},3}
        D̄::Array{T,3}
        traceless_adiabatic_derivative::Array{Matrix{T},3}

        centroid::Matrix{T}
        centroid_potential::Hermitian{T,Matrix{T}}
        centroid_derivative::Matrix{Hermitian{T,Matrix{T}}}
        centroid_eigen::LinearAlgebra.Eigen{T, T, Matrix{T}, Vector{T}}
        centroid_adiabatic_derivative::Matrix{Matrix{T}}
        centroid_nonadiabatic_coupling::Matrix{Matrix{T}}



Struct of type Abstract_QuantumModel_Cache, used to store quantities (of data types `T`, `S` and `L`) generated by its input model `M`.
"""
struct RingPolymer_QuantumFrictionModel_Cache{M, VHMtx, ArrHMtx, VEig, Vec, ArrMtx, Mtx, Arr, HMtx, MHMtx, Eig, MtxMtx, VecVec, MtxHMtx} <: Abstract_QuantumModel_Cache{M}
    model::M
    friction_method::FrictionEvaluationMethod
    potential::VHMtx
    derivative::ArrHMtx
    eigen::VEig
    phase_ref::VecVec
    adiabatic_derivative::ArrMtx
    nonadiabatic_coupling::ArrMtx
    friction::ArrMtx
    tmp_mat::Mtx

    traceless_potential::VHMtx
    V̄::Vec
    traceless_derivative::ArrHMtx
    D̄::Arr
    traceless_adiabatic_derivative::ArrMtx

    centroid::Mtx
    centroid_potential::HMtx
    centroid_derivative::MtxHMtx
    centroid_eigen::Eig
    centroid_phase_ref::Vec
    centroid_adiabatic_derivative::MtxMtx
    centroid_nonadiabatic_coupling::MtxMtx
    centroid_friction::Mtx
end

Adapt.@adapt_structure RingPolymer_QuantumFrictionModel_Cache

"""
    function: RingPolymer_QuantumModel_Cache{T}(model::M, atoms::Integer, beads::Integer) where {T,M<:Model}

Function which constructs and returns the Struct of the same name. Takes as input an adiabatic model `M` of the users choice,
the number of atoms in the simulation and the number of beads used in the ring polymer simulation.
"""
function RingPolymer_QuantumFrictionModel_Cache(model::M, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}; friction_method::FrictionEvaluationMethod) where {M<:Model, T, N}
    n = nstates(model)
    mat = NQCModels.QuantumModels.matrix_template(model, eltype(matrix_prototype))
    vec = NQCModels.QuantumModels.vector_template(model, eltype(matrix_prototype))

    potential = [similar_zero(matrix_prototype, size(mat)) for _=1:beads]
    derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    eigen = [(similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat))) for _=1:beads]
    phase_ref = [similar_but_random(matrix_prototype, n) .+ eps(T) for _=1:beads]
    nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    friction = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    tmp_mat = similar_zero(matrix_prototype, size(mat))

    traceless_potential = [similar_zero(matrix_prototype, size(mat)) for _=1:beads]
    V̄ = similar_zero(vec, beads)
    traceless_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]
    D̄ = similar_zero(matrix_prototype, atoms, beads)
    traceless_adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms, _=1:beads]

    centroid = similar_zero(matrix_prototype, ndofs(model), atoms)
    centroid_potential = similar_zero(matrix_prototype, size(mat))
    centroid_derivative = [similar_zero(matrix_prototype, size(mat)) for _=1:ndofs(model), _=1:atoms]
    centroid_eigen = (similar_zero(matrix_prototype, size(vec)), similar_zero(matrix_prototype, size(mat)))
    centroid_phase_ref = similar_but_random(matrix_prototype, n) .+ eps(T)
    centroid_adiabatic_derivative = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(centroid_derivative)]
    centroid_nonadiabatic_coupling = [similar_zero(matrix_prototype, size(mat)) for _ in CartesianIndices(centroid_derivative)]
    centroid_friction = similar_zero(matrix_prototype, ndofs(model)*atoms, ndofs(model)*atoms)

    return RingPolymer_QuantumFrictionModel_Cache(
        model,
        friction_method,
        potential,
        derivative,
        eigen,
        phase_ref,
        adiabatic_derivative,
        nonadiabatic_coupling,
        friction,
        tmp_mat,

        traceless_potential,
        V̄,
        traceless_derivative,
        D̄,
        traceless_adiabatic_derivative,

        centroid,
        centroid_potential,
        centroid_derivative,
        centroid_eigen,
        centroid_phase_ref,
        centroid_adiabatic_derivative,
        centroid_nonadiabatic_coupling,
        centroid_friction
    )
end


#Multiple dispatch definitions of the Create_Cache function with creates a Cache of the appropriate type dependent on what model type it is given
function Create_Cache(model::ClassicalModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {T, N}  #functions of this type were called Calculator(model, atoms, t)
    ClassicalModel_Cache(model, atoms, matrix_prototype)
end

function Create_Cache(model::ClassicalModel, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {T, N}
    RingPolymer_ClassicalModel_Cache(model, atoms, beads, matrix_prototype)
end

function Create_Cache(model::ClassicalFrictionModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    ClassicalFrictionModel_Cache(model, atoms, matrix_prototype)
end

function Create_Cache(model::ClassicalFrictionModel, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    RingPolymer_ClassicalFrictionModel_Cache(model, atoms, beads, matrix_prototype)
end

function Create_Cache(model::CompositeModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    if any([!isa(s.model, ClassicalModel) for s in NQCModels.get_pes_models(model.subsystems)])
        throw(ArgumentError("Currently, only CompositeModels using ClassicalModels to supply a PES are supported. "))
    end
    ClassicalFrictionModel_Cache(model, atoms, matrix_prototype)
end

function Create_Cache(model::CompositeModel, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    if any([!isa(s.model, ClassicalModel) for s in NQCModels.get_pes_models(model.subsystems)])
        throw(ArgumentError("Currently, only CompositeModels using ClassicalModels to supply a PES are supported. "))
    end
    RingPolymer_ClassicalFrictionModel_Cache(model, atoms, beads, matrix_prototype)
end

function Create_Cache(model::QuantumModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    QuantumModel_Cache(model, atoms, matrix_prototype)
end

function Create_Cache(model::QuantumModel, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}) where {T,N}
    RingPolymer_QuantumModel_Cache(model, atoms, beads, matrix_prototype)
end

# specific multiple dispatch for AndersonHolstein to work with DiabaticMDEF, friction_methods needs to not be a keyword argument
function Create_Cache(model::QuantumModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}, friction_method::Union{FrictionEvaluationMethod, Nothing}) where {T,N}
    QuantumFrictionModel_Cache(model, atoms, matrix_prototype; friction_method=friction_method)
end

function Create_Cache(model::QuantumFrictionModel, atoms::Integer, matrix_prototype::AbstractArray{T,N}; friction_method::Union{FrictionEvaluationMethod, Nothing}=nothing) where {T,N}
    QuantumFrictionModel_Cache(model, atoms, matrix_prototype; friction_method=friction_method)
end

function Create_Cache(model::QuantumFrictionModel, atoms::Integer, beads::Integer, matrix_prototype::AbstractArray{T,N}; friction_method::Union{FrictionEvaluationMethod, Nothing}=nothing) where {T,N}
    RingPolymer_QuantumFrictionModel_Cache(model, atoms, beads, matrix_prototype; friction_method=friction_method)
end